package com.multistore.core.remoteconfig

import java.security.SecureRandom
import java.util.Base64
import kotlin.time.Clock
import kotlin.time.Instant
import org.bouncycastle.crypto.generators.Ed25519KeyPairGenerator
import org.bouncycastle.crypto.params.Ed25519KeyGenerationParameters
import org.bouncycastle.crypto.params.Ed25519PrivateKeyParameters
import org.bouncycastle.crypto.params.Ed25519PublicKeyParameters
import org.bouncycastle.crypto.signers.Ed25519Signer

/**
 * A key pair generated by the test, and the envelope that comes out of it.
 *
 * The keys are generated **here** and not read from a file: a fixture with a private key inside would
 * be a private key in the repository, and the distinction between "this is a test one" and "this is
 * the real one" would depend on a comment. Generating them also makes the test that matters most
 * trivial — signing with the wrong key — because a second pair is all it takes.
 */
class SigningFixture(seed: Long = 1) {

    private val pair = Ed25519KeyPairGenerator().apply {
        init(Ed25519KeyGenerationParameters(SecureRandom.getInstance("SHA1PRNG").apply { setSeed(seed) }))
    }.generateKeyPair()

    val publicKey: ByteArray = (pair.public as Ed25519PublicKeyParameters).encoded
    private val privateKey = pair.private as Ed25519PrivateKeyParameters

    fun sign(payload: ByteArray): ByteArray = Ed25519Signer().apply {
        init(true, privateKey)
        update(payload, 0, payload.size)
    }.generateSignature()

    /** The envelope as `tools/sign-config.sh` produces it. */
    fun envelope(document: String, algorithm: String = "ed25519"): ByteArray {
        val payload = document.encodeToByteArray()
        val encoder = Base64.getEncoder()
        val json = """{"algorithm":"$algorithm",""" +
            """"payload":"${encoder.encodeToString(payload)}",""" +
            """"signature":"${encoder.encodeToString(sign(payload))}"}"""
        return json.encodeToByteArray()
    }

    fun documents(): SignedDocuments = SignedDocuments(publicKey)
}

/** A stopped clock: tests never let real time pass. */
class FixedClock(private var instant: Instant = Instant.parse("2026-08-25T10:00:00Z")) : Clock {
    override fun now(): Instant = instant
    fun advanceTo(value: Instant) { instant = value }
}
