#!/usr/bin/env bash
#
# Builds the signed release and derives the `selfUpdate` block of `index.json` from it.
#
#   tools/release.sh [output.json]
#
# The `selfUpdate` block is written by whoever builds the release, because they are the only one
# who knows the APK's versionCode, hash and size. Those values used to be copied by hand into a
# **signed** document that every installation applies. A wrong hash there does not produce a syntax
# error: it produces an update every user downloads and that verification refuses.
#
# The four values are therefore read **from the APK**, not from `build.gradle.kts`. They are the
# same thing until somebody gets it wrong, and this script exists for that case.
#
# If the APK is not signed, it stops. Without `.secrets/keystore.properties` the `release` variant
# comes out unsigned on purpose — see `app/build.gradle.kts` — and an unsigned APK published as an
# update is an update no device will install.
set -euo pipefail

out="${1:--}"
here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

: "${JAVA_HOME:?JAVA_HOME is not set. There may be no system JDK on this machine: use the one bundled with Android Studio.}"
: "${ANDROID_HOME:=$HOME/Library/Android/sdk}"

# The most recent build-tools installed: `aapt2` and `apksigner` live there and not on the PATH.
tools="$(ls -d "$ANDROID_HOME"/build-tools/*/ 2>/dev/null | sort -V | tail -1)"
[ -n "$tools" ] || { echo "no build-tools in $ANDROID_HOME/build-tools" >&2; exit 1; }
aapt2="$tools/aapt2"
apksigner="$tools/apksigner"

echo "==> build release" >&2
(cd "$here" && ./gradlew :app:assembleRelease)

# The file name is given by AGP in `output-metadata.json`, and is not guessable: a **signed**
# release is called `app-release.apk`, an unsigned one `app-release-unsigned.apk`. Writing the
# first by hand made the script fail with "APK not produced" in exactly the case it has to
# diagnose instead — that is, the missing signature.
outputs="$here/app/build/outputs/apk/release"
name="$(sed -n 's/.*"outputFile": "\([^"]*\)".*/\1/p' "$outputs/output-metadata.json" | head -1)"
apk="$outputs/$name"
[ -f "$apk" ] || { echo "APK not produced: $apk" >&2; exit 1; }

echo "==> verifying the signature" >&2
if ! "$apksigner" verify --print-certs "$apk" >/dev/null 2>&1; then
  cat >&2 <<'MSG'
The APK is not signed.

The `release` variant takes the key from `.secrets/keystore.properties`, which is not in the
repository. Without that file it comes out unsigned on purpose — see `app/build.gradle.kts`.

To create one:

    keytool -genkeypair -v -keystore .secrets/multistore-release.jks \
      -alias multistore -keyalg RSA -keysize 4096 -validity 10000

then `.secrets/keystore.properties` with storeFile / storePassword / keyAlias / keyPassword.

**The key must not be lost and must not be changed**: it is the identity every installation is
tied to. Changing it means no device will be able to update the app any more — Android refuses an
update signed by a different key — and the only way out for whoever has it installed would be to
uninstall, losing their data.
MSG
  exit 1
fi

# `aapt2 dump badging` and not `build.gradle.kts`: the two values coincide until somebody gets it
# wrong, and this script exists for that case.
badging="$("$aapt2" dump badging "$apk")"
version_code="$(sed -n "s/.*versionCode='\([0-9]*\)'.*/\1/p" <<<"$badging" | head -1)"
version_name="$(sed -n "s/.*versionName='\([^']*\)'.*/\1/p" <<<"$badging" | head -1)"
# `minSdkVersion:` and not `sdkVersion:` — with the latter the first matching field is
# `targetSdkVersion`, and with the wrong anchor nothing matches at all. The first draft wrote
# `"minSdk": ,` — **invalid JSON inside a signed document**, that is exactly the class of error
# this script exists for. Hence the check below.
min_sdk="$(sed -n "s/^minSdkVersion:'\([0-9]*\)'.*/\1/p" <<<"$badging" | head -1)"

for pair in "versionCode:$version_code" "versionName:$version_name" "minSdk:$min_sdk"; do
  if [ -z "${pair#*:}" ]; then
    echo "not read from the APK: ${pair%%:*}. \`aapt2 dump badging\` has changed format." >&2
    exit 1
  fi
done

size="$(wc -c < "$apk" | tr -d ' ')"
sha256="$(shasum -a 256 "$apk" | cut -d' ' -f1)"

signer="$("$apksigner" verify --print-certs "$apk" | sed -n 's/.*certificate SHA-256 digest: //p' | head -1)"

: "${MULTISTORE_RELEASE_URL:=https://example.invalid/multistore-$version_name.apk}"

# `notes` is not written by this script: it is prose, and prose generated by a script is prose
# nobody wrote. It is added to the document by hand, or left out.
envelope=$(cat <<JSON
{
  "versionCode": $version_code,
  "versionName": "$version_name",
  "minSdk": $min_sdk,
  "url": "$MULTISTORE_RELEASE_URL",
  "sha256": "$sha256",
  "size": $size
}
JSON
)

{
  echo
  echo "APK        : $apk"
  echo "versionCode: $version_code   versionName: $version_name   minSdk: $min_sdk"
  echo "size       : $size bytes"
  echo "sha256     : $sha256"
  echo "signer     : $signer"
  echo
  echo "The signer is what the app will compare against the **already-installed certificate**:"
  echo "if it does not match, the update is refused and the user has no way out."
  echo
  echo "Next steps:"
  echo "  1. upload the APK to: $MULTISTORE_RELEASE_URL"
  echo "     (the address is chosen with the MULTISTORE_RELEASE_URL environment variable)"
  echo "  2. ./gradlew :tools:index:buildIndex --args=\"build/index-payload.json <ISO8601> <this file>\""
  echo "  3. tools/sign-config.sh build/index-payload.json .secrets/parsers-ed25519.pem index.json"
  echo "  4. publish index.json, and verify with a minified build (see tools/README.md)"
  echo
} >&2

if [ "$out" = "-" ]; then
  printf '%s\n' "$envelope"
else
  printf '%s\n' "$envelope" > "$out"
  echo "selfUpdate block written to: $out" >&2
fi
