package com.multistore.core.database.dao

import androidx.paging.PagingSource
import androidx.room.Dao
import androidx.room.ColumnInfo
import androidx.room.Embedded
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Update
import androidx.room.Query
import androidx.room.Transaction
import androidx.room.Upsert
import com.multistore.core.database.entity.AppEntity
import com.multistore.core.database.entity.AppVersionEntity
import com.multistore.core.database.entity.IdentityOverrideEntity
import com.multistore.core.database.entity.ListingScreenshotEntity
import com.multistore.core.database.entity.StoreListingEntity
import com.multistore.core.model.ContentKind
import com.multistore.core.model.MatchMethod
import com.multistore.core.model.StoreId
import kotlinx.coroutines.flow.Flow

/**
 * A listing ready to write: the aggregated app, the listing, the versions, the screenshots.
 *
 * It lives here and not in `:core:data` because it is the argument of a transaction, and the
 * transaction must live inside Room: managing it from outside would mean either one transaction
 * per row — 4,257 fsyncs for one sync — or a `withTransaction` opened by someone who does not know
 * how long it will last.
 */
data class ListingWrite(
    val app: AppEntity,
    val listing: StoreListingEntity,
    val versions: List<AppVersionEntity>,
    val screenshots: List<ListingScreenshotEntity>,
)

/**
 * A listing as it appears in a **list**: the row plus the aggregated app's icon.
 *
 * The icon lives on `apps` and not on `store_listings` because it is a property of the app, not of
 * the individual listing: with nine stores publishing the same app it comes from whichever
 * publishes it best. A list still has to show it, and reading it with one query per row would be
 * thirty queries per page: hence the join.
 *
 * It does not carry the version, deliberately: the version to show is not the highest
 * `versionCode` — across 4,257 F-Droid packages there are **14** where the two differ — and the
 * rule that picks it needs the device and the installed signer, things a list query does not have.
 * A number in the row that the listing then contradicts is worse than no number.
 */
/** The icon the catalogue knows for a listing. See [CatalogDao.iconsOf]. */
data class KnownIcon(
    @ColumnInfo(name = "store_app_ref") val storeAppRef: String,
    @ColumnInfo(name = "icon_url") val iconUrl: String?,
)

data class ListingRow(
    @Embedded val listing: StoreListingEntity,
    @ColumnInfo(name = "icon_url") val iconUrl: String?,
)

/**
 * A listing's row identity: its id and the aggregated app's key.
 *
 * It exists so a whole listing — versions and screenshots included — need not be read when all
 * that is wanted is "the installed app updates from this listing". The update channel is a
 * multi-store fact: an app taken from one store must be updated **from that same store**, because
 * the first store with a higher versionCode would almost always have a different signer and the
 * update would fail at OS level.
 */
data class ListingIdentity(
    @ColumnInfo(name = "id") val listingId: Long,
    @ColumnInfo(name = "app_key") val appKey: String,
)

/** A listing with everything needed to draw its screen, in a single read. */
data class ListingWithDetails(
    @Embedded val listing: StoreListingEntity,
    @androidx.room.Relation(parentColumn = "id", entityColumn = "listing_id")
    val versions: List<AppVersionEntity>,
    @androidx.room.Relation(parentColumn = "id", entityColumn = "listing_id")
    val screenshots: List<ListingScreenshotEntity>,
)

@Dao
interface CatalogDao {

    @Upsert
    suspend fun upsertApps(apps: List<AppEntity>)

    @Insert
    suspend fun insertListing(listing: StoreListingEntity): Long

    @Update
    suspend fun updateListing(listing: StoreListingEntity)

    /**
     * Saves a listing with its versions and screenshots, preserving its id.
     *
     * Not an `@Upsert`, and the reason is a Room trap worth writing down: `@Upsert` tries an insert
     * and, if it fails, updates **by primary key**. Here the primary key is an autogenerated id
     * while the conflict occurs on the unique index `(store_id, store_app_ref)`: the update would
     * look for the row with `id = 0` and find nothing. The result would be a lost write, silently.
     *
     * Preserving the id matters in its own right too: `installed_apps.update_channel_listing_id`
     * points at it, and recreating it on every sync would detach every installed app from its
     * update channel.
     */
    @Transaction
    suspend fun saveListing(
        listing: StoreListingEntity,
        versions: List<AppVersionEntity>,
        screenshots: List<ListingScreenshotEntity>,
    ): Long {
        val existing = listingId(listing.storeId, listing.storeAppRef)
        val id = if (existing != null) {
            updateListing(listing.copy(id = existing))
            existing
        } else {
            insertListing(listing.copy(id = 0))
        }
        clearVersions(id)
        clearScreenshots(id)
        if (versions.isNotEmpty()) upsertVersions(versions.map { it.copy(id = 0, listingId = id) })
        if (screenshots.isNotEmpty()) upsertScreenshots(screenshots.map { it.copy(id = 0, listingId = id) })
        return id
    }

    /**
     * Writes a batch of listings in **one** transaction.
     *
     * The caller chooses the batch size, between two evils: one transaction per row costs an fsync
     * per row, one transaction for the whole sync keeps the database in write for a minute — and in
     * that minute an in-flight installation cannot record its outcome.
     *
     * Apps must be inserted before listings: `store_listings.app_key` is a foreign key, and Room
     * keeps constraints on.
     */
    @Transaction
    suspend fun saveListings(writes: List<ListingWrite>) {
        if (writes.isEmpty()) return
        upsertApps(writes.map { it.app }.distinctBy { it.appKey })
        for (write in writes) {
            saveListing(write.listing, write.versions, write.screenshots)
        }
    }

    @Query("SELECT id FROM store_listings WHERE store_id = :storeId AND store_app_ref = :ref")
    suspend fun listingId(storeId: StoreId, ref: String): Long?

    /**
     * Writes a listing **only if that store does not already have one** with that reference.
     *
     * Used by cross-store matching, which discovers listings by reading a **results page**: there
     * are neither versions nor screenshots there, and going through [saveListing] would be a silent
     * disaster — that method calls `clearVersions`, so rediscovering an already-open listing would
     * delete its versions and the listing would say "this store publishes no installable package"
     * for an app that has ten.
     *
     * It returns the id, new or existing: the caller needs it to record any user correction in
     * `identity_overrides`.
     */
    @Transaction
    suspend fun insertListingIfAbsent(listing: StoreListingEntity): Long {
        val existing = listingId(listing.storeId, listing.storeAppRef)
        return existing ?: insertListing(listing.copy(id = 0))
    }

    /**
     * The other listings of the **same** aggregated app.
     *
     * This is the query behind "available on N stores": `app_key` is already shared by whatever
     * merged, so no comparison needs redoing — the match has already been decided and written.
     */
    @Query(
        """
        SELECT l.*, a.icon_url AS icon_url FROM store_listings AS l
        LEFT JOIN apps AS a ON a.app_key = l.app_key
        WHERE l.app_key = :appKey AND l.id != :excludingListingId
        ORDER BY l.store_id
        """,
    )
    suspend fun siblings(appKey: String, excludingListingId: Long): List<ListingRow>

    @Query(
        """
        SELECT l.*, a.icon_url AS icon_url FROM store_listings AS l
        LEFT JOIN apps AS a ON a.app_key = l.app_key
        WHERE l.app_key = :appKey AND l.id != :excludingListingId
        ORDER BY l.store_id
        """,
    )
    fun observeSiblings(appKey: String, excludingListingId: Long): Flow<List<ListingRow>>

    /**
     * The listings that **might** be the same app, to hand to the matcher.
     *
     * The filter is deliberately crude — the prefix of the normalised title, which is indexed — and
     * decides nothing: it exists only to keep the comparison from running over every row in the
     * catalogue. `IdentityMatcher` decides, in memory, over the few rows that come back.
     *
     * The prefix is short on purpose. With four characters `duckduckgo` and `duck duck go` both
     * fall under `duck`, and they are exactly the pair a comparison of whole titles would miss.
     */
    @Query(
        """
        SELECT l.*, a.icon_url AS icon_url FROM store_listings AS l
        LEFT JOIN apps AS a ON a.app_key = l.app_key
        WHERE l.app_key != :excludingAppKey AND l.title_norm LIKE :titlePrefix || '%'
        ORDER BY l.store_id
        LIMIT :limit
        """,
    )
    suspend fun listingsWithSimilarTitle(
        titlePrefix: String,
        excludingAppKey: String,
        limit: Int = 60,
    ): List<ListingRow>

    /**
     * Moves a listing onto another aggregated app, with the confidence that decided it.
     *
     * This is what happens when the user confirms a "possible match": from then on the listing
     * **is** that app, and the siblings query finds it without redoing any comparison.
     */
    @Query(
        """
        UPDATE store_listings
        SET app_key = :appKey, match_confidence = :confidence, match_method = :method
        WHERE id = :listingId
        """,
    )
    suspend fun reassignListing(
        listingId: Long,
        appKey: String,
        confidence: Float,
        method: MatchMethod,
    )

    /** The user's correction to a match. One per listing: the last wins. */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertIdentityOverride(override: IdentityOverrideEntity)

    @Query("SELECT * FROM identity_overrides WHERE app_key = :appKey")
    suspend fun identityOverrides(appKey: String): List<IdentityOverrideEntity>

    @Query("SELECT * FROM identity_overrides WHERE app_key = :appKey")
    fun observeIdentityOverrides(appKey: String): Flow<List<IdentityOverrideEntity>>

    /**
     * A listing's title, and nothing else.
     *
     * Read by the download notification: "Downloading AntennaPod" instead of
     * "de.danoeh.antennapod". A single read at the start of the transfer, so it is not worth
     * loading the whole listing with versions and screenshots to get one string.
     */
    @Query("SELECT title FROM store_listings WHERE id = :listingId")
    suspend fun listingTitle(listingId: Long): String?

    /**
     * The icons the catalogue already knows for these listings.
     *
     * Used by search, on the rows a store does not supply an icon for — on apkmody, all of them.
     * Only `ref -> icon`: a `SELECT *` would load listing, versions and screenshots to fetch a
     * string, which is the same reason [listingTitle] exists.
     *
     * **The icon lives on `apps`, not on `store_listings`**, so it belongs to the aggregated app
     * and not to the individual listing: whoever shares an `app_key` shares the icon. In the case
     * this query exists for the two coincide — the app in question has a single listing — and where
     * they do not, the match is one `IdentityMatcher` has already accepted. Worth knowing all the
     * same: it is the same place where `content_kind` used to be overwritten by the last listing
     * saved, and there the damage was a filter that found nothing. Here the worst damage is a wrong
     * image next to a right title.
     */
    @Query(
        """
        SELECT l.store_app_ref AS store_app_ref, a.icon_url AS icon_url
        FROM store_listings AS l
        JOIN apps AS a ON a.app_key = l.app_key
        WHERE l.store_id = :storeId AND l.store_app_ref IN (:refs) AND a.icon_url IS NOT NULL
        """,
    )
    suspend fun iconsOf(storeId: StoreId, refs: List<String>): List<KnownIcon>

    @Query("DELETE FROM app_versions WHERE listing_id = :listingId")
    suspend fun clearVersions(listingId: Long)

    @Query("DELETE FROM listing_screenshots WHERE listing_id = :listingId")
    suspend fun clearScreenshots(listingId: Long)

    /**
     * Inserts the versions, replacing those with the same `version_ref`.
     *
     * `@Insert(REPLACE)` and not `@Upsert`, for the reason explained on [saveListing]: `@Upsert`
     * updates **by primary key**, which here is an autogenerated id, while the conflict occurs on
     * the unique index `(listing_id, version_ref)`. The result would be that the old row stays and
     * the new one is ignored — an updated version that never appears, with no error.
     *
     * `REPLACE` deletes and reinserts, so the id changes: acceptable because nobody points at a
     * version's id. Whoever needs one uses `version_ref`, which is stable.
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertVersions(versions: List<AppVersionEntity>)

    /**
     * Adds versions to a listing **without deleting the ones already there**.
     *
     * The opposite of [saveListing], which starts with [clearVersions] because it is rewriting what
     * the listing declares now. Here the source is a different one — the version-history page,
     * which three stores out of nine publish separately — and what it brings **adds up**: on
     * apkcombo the listing declares one version and `/old-versions` lists dozens.
     *
     * The conflict is resolved by the unique index `(listing_id, version_ref)`: a version both
     * sources name is replaced, not duplicated. If the listing is not (or no longer) in the
     * catalogue nothing is written: a version without its listing would be read by nobody, and the
     * foreign key would refuse it.
     */
    @Transaction
    suspend fun mergeVersions(storeId: StoreId, ref: String, versions: List<AppVersionEntity>) {
        if (versions.isEmpty()) return
        val id = listingId(storeId, ref) ?: return
        upsertVersions(versions.map { it.copy(id = 0, listingId = id) })
    }

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertScreenshots(screenshots: List<ListingScreenshotEntity>)

    @Query("DELETE FROM store_listings WHERE store_id = :storeId AND store_app_ref IN (:refs)")
    suspend fun deleteListings(storeId: StoreId, refs: List<String>)

    @Query("DELETE FROM store_listings WHERE store_id = :storeId")
    suspend fun clearListings(storeId: StoreId)

    /**
     * Removes aggregated apps that no longer have any listing.
     *
     * Without it, every package withdrawn from a store would leave a row in `apps` behind forever:
     * invisible, never deleted, and able to attract onto itself the match of a listing from another
     * store that has nothing to do with that app.
     */
    @Query("DELETE FROM apps WHERE app_key NOT IN (SELECT app_key FROM store_listings)")
    suspend fun deleteOrphanApps(): Int

    /**
     * Deletes listings expired long enough, and **only** those nobody claims.
     *
     * ### The five clauses, and what removing one would let through
     *
     * They are not accumulated caution: each covers a case the others do not see, and four of the
     * five concern rows that are not cache at all.
     *
     *  - **`store_id NOT IN (:indexedStores)`** — a locally-indexed store has no "downloaded
     *    listings": its rows in `store_listings` are **projections** of the index, and the source
     *    stays in `store_index_entries`. Deleting them would not free the source and would break
     *    that store's search until the next sync. Measured 26/08/2026: 4,268 of the 4,279 listings
     *    on the device were F-Droid's, so without this clause the automatic purge would do exactly
     *    the maximum damage for the minimum benefit;
     *  - **the update channel** — `installed_apps.update_channel_listing_id` has no foreign key, and
     *    must not have one: a package withdrawn from the store is no reason to forget the user has
     *    it installed. That dangling pointer is tolerated when the store produces it, not when we
     *    produce it ourselves to save two kilobytes;
     *  - **the provenance** — the same thing seen through the other key: `installed_apps` remembers
     *    provenance as `(store_id, ref)`, not as a row id;
     *  - **downloads** — a download outlives the listing that produced it, and its row names it by
     *    id;
     *  - **`identity_overrides`** — the only clause that protects a **user decision**: whoever
     *    confirmed or rejected a cross-store match did so once, and deleting the listing would ask
     *    them the same question all over again.
     *
     * ### Why `expiresBefore` and not "expired"
     *
     * An expired listing is not useless: search shows it immediately while re-fetching —
     * stale-while-revalidate — so deleting it the instant it expires would empty exactly the first
     * moment yesterday's search is reopened. The parameter is the instant before which the
     * **expiry** must have fallen, i.e. `now - retention`.
     *
     * `fetched_at` is in milliseconds (see `Converters`), `ttl_seconds` in seconds: the factor of a
     * thousand is in the query and not in the caller because it is a fact of the schema.
     *
     * ### One query for the automatic purge and for the button
     *
     * The "clear the downloaded catalogue" button comes through here with `indexedStores` empty and
     * `expiresBeforeMillis = Long.MAX_VALUE`: no store excluded, no expiry to wait for. It is
     * deliberately **the same** query, because the five protections above hold identically in both
     * cases — a button that, to free space, detached every installed app's update channel would be
     * worse than the problem it solves — and two copies of the same clause are two copies that can
     * diverge.
     *
     * SQLite allows `NOT IN ()` with an empty list, unlike almost every other engine: that is what
     * makes the "no store excluded" parameter possible without a second query.
     */
    @Query(
        """
        DELETE FROM store_listings
        WHERE store_id NOT IN (:indexedStores)
          AND (fetched_at + ttl_seconds * 1000) < :expiresBeforeMillis
          AND id NOT IN (
              SELECT update_channel_listing_id FROM installed_apps
              WHERE update_channel_listing_id IS NOT NULL
          )
          AND NOT EXISTS (
              SELECT 1 FROM installed_apps ia
              WHERE ia.source_store_id = store_listings.store_id
                AND ia.source_ref = store_listings.store_app_ref
          )
          AND id NOT IN (SELECT listing_id FROM downloads)
          AND id NOT IN (SELECT listing_id FROM identity_overrides)
        """,
    )
    suspend fun deletePurgeableListings(indexedStores: List<StoreId>, expiresBeforeMillis: Long): Int

    @Query(
        """
        SELECT id, app_key FROM store_listings
        WHERE store_id = :storeId AND store_app_ref = :ref
        LIMIT 1
        """,
    )
    suspend fun listingIdentity(storeId: StoreId, ref: String): ListingIdentity?

    @Query("SELECT * FROM apps WHERE app_key = :appKey")
    suspend fun app(appKey: String): AppEntity?

    @Transaction
    @Query("SELECT * FROM store_listings WHERE store_id = :storeId AND store_app_ref = :ref")
    suspend fun listing(storeId: StoreId, ref: String): ListingWithDetails?

    @Transaction
    @Query("SELECT * FROM store_listings WHERE store_id = :storeId AND store_app_ref = :ref")
    fun observeListing(storeId: StoreId, ref: String): Flow<ListingWithDetails?>

    /**
     * Search over the local index.
     *
     * A `LIKE` on an indexed column rather than FTS4: across 4,257 rows the difference is a few
     * milliseconds, while an FTS table costs space, another table to keep aligned and another
     * migration when the schema changes. If indexed stores ever bring hundreds of thousands of
     * rows, that will be the moment to change — and it will be a change internal to this DAO.
     *
     * The ordering puts whoever **starts** with the search term first: someone typing "tor" wants
     * Tor Browser before Calculator (which contains "tor" inside "Calculator").
     *
     * ### The filters are applied here by the database, and before that nobody applied them
     *
     * F-Droid declares seven `FilterCapability`s and its adapter's `search` ignores them — rightly,
     * because that is the fallback search and the remote API accepts no filters. The capability
     * says "the local index applies them", i.e. **this query**, which used not to receive the
     * filters as arguments at all. It was the third side of a triangle with two sides: the
     * capability was there, the UI adapted to it, and in between nothing filtered.
     *
     * Applying them here rather than to the rows that come back is not an optimisation: `LIMIT`
     * runs **after** `WHERE`, so filtering downstream a page of twenty might return three, and the
     * next page would restart from a point that does not account for the discarded ones.
     *
     * [orderByName] and not the whole enum, on purpose: ordering by rating on the one indexed store
     * would be an `ORDER BY` on a column F-Droid populates on no row, i.e. a branch no
     * configuration walks. Relevance stays the default and is the order the two `CASE`s below
     * produce.
     */
    @Query(
        """
        SELECT l.*, a.icon_url AS icon_url FROM store_listings AS l
        LEFT JOIN apps AS a ON a.app_key = l.app_key
        WHERE l.store_id = :storeId
          AND (l.title_norm LIKE '%' || :query || '%' OR l.store_app_ref LIKE '%' || :query || '%')
          AND (:kind IS NULL OR l.content_kind = :kind)
          AND (:minRating IS NULL OR (l.rating IS NOT NULL AND l.rating >= :minRating))
        ORDER BY
          CASE WHEN :orderByName THEN 0
               WHEN l.title_norm = :query THEN 0
               WHEN l.title_norm LIKE :query || '%' THEN 1
               ELSE 2 END,
          l.title_norm
        LIMIT :limit OFFSET :offset
        """,
    )
    suspend fun search(
        storeId: StoreId,
        query: String,
        limit: Int,
        offset: Int,
        kind: ContentKind? = null,
        minRating: Float? = null,
        orderByName: Boolean = false,
    ): List<ListingRow>

    /**
     * How many rows [search] would find in total.
     *
     * The predicates are the same, and must stay so: this count decides `hasMore`, so a filter
     * applied there and not here would produce a page claiming "more" when there is none, or —
     * worse — a list that stops before the end.
     */
    @Query(
        """
        SELECT COUNT(*) FROM store_listings
        WHERE store_id = :storeId
          AND (title_norm LIKE '%' || :query || '%' OR store_app_ref LIKE '%' || :query || '%')
          AND (:kind IS NULL OR content_kind = :kind)
          AND (:minRating IS NULL OR (rating IS NOT NULL AND rating >= :minRating))
        """,
    )
    suspend fun searchCount(
        storeId: StoreId,
        query: String,
        kind: ContentKind? = null,
        minRating: Float? = null,
    ): Int

    /** Recently updated apps: feeds Home without a single network request. */
    @Query(
        """
        SELECT l.*, a.icon_url AS icon_url FROM store_listings AS l
        LEFT JOIN apps AS a ON a.app_key = l.app_key
        WHERE l.store_id = :storeId AND l.last_updated IS NOT NULL
        ORDER BY l.last_updated DESC
        LIMIT :limit OFFSET :offset
        """,
    )
    suspend fun recentlyUpdated(storeId: StoreId, limit: Int, offset: Int): List<ListingRow>

    @Query(
        """
        SELECT l.*, a.icon_url AS icon_url FROM store_listings AS l
        LEFT JOIN apps AS a ON a.app_key = l.app_key
        WHERE l.store_id = :storeId AND l.categories LIKE '%"' || :category || '"%'
        ORDER BY l.title_norm
        LIMIT :limit OFFSET :offset
        """,
    )
    suspend fun byCategory(storeId: StoreId, category: String, limit: Int, offset: Int): List<ListingRow>

    /**
     * How many listings sit in a category.
     *
     * It is what **orders** the categories, and without it they cannot be: F-Droid publishes 108,
     * declares an `app_count` for none, and alphabetically the first three are "AI Chat", "Action
     * Game" and "Alarm Clock" — three categories of a few dozen apps ahead of "System", which has
     * 629.
     *
     * The predicate is deliberately the same as [byCategory]'s: two different ways of recognising
     * membership of a category would give a count that does not match the list.
     */
    @Query(
        """
        SELECT COUNT(*) FROM store_listings
        WHERE store_id = :storeId AND categories LIKE '%"' || :category || '"%'
        """,
    )
    suspend fun categoryCount(storeId: StoreId, category: String): Int

    /**
     * Every listing of one store, in alphabetical order.
     *
     * The only query that makes the local index **browsable** rather than merely searchable:
     * without it the 4,269 already-downloaded packages are reachable only by already knowing what
     * you are looking for. The order is on `title_norm`, which is indexed, and not on `title`: the
     * normalised column is the same one that orders search, so the two lists do not contradict
     * each other on accents and case.
     */
    @Query(
        """
        SELECT l.*, a.icon_url AS icon_url FROM store_listings AS l
        LEFT JOIN apps AS a ON a.app_key = l.app_key
        WHERE l.store_id = :storeId
        ORDER BY l.title_norm
        LIMIT :limit OFFSET :offset
        """,
    )
    suspend fun listings(storeId: StoreId, limit: Int, offset: Int): List<ListingRow>

    /**
     * The same rows as [listings], **paged, and with invalidation**.
     *
     * ### Why a second query and not the first with a different `LIMIT`
     *
     * Room writes the `LIMIT`/`OFFSET`, and with it the count query needed to know when the list
     * ends. What is really gained is not the paging — that already existed, by hand, in the
     * ViewModel — but **invalidation**: a Room-generated `PagingSource` invalidates itself when
     * `store_listings` changes, and the list reloads. With the in-memory accumulation that came
     * before, an index sync while the user was browsing left a stale catalogue on screen **forever**
     * — until they left and came back — and nothing said so.
     *
     * ### Why [listings] stays
     *
     * Home uses it, and Home shows one page and never a second. A `PagingSource` for a list of ten
     * items is a `Flow` and a `RemoteMediator` of machinery for nothing.
     */
    @Query(
        """
        SELECT l.*, a.icon_url AS icon_url FROM store_listings AS l
        LEFT JOIN apps AS a ON a.app_key = l.app_key
        WHERE l.store_id = :storeId
        ORDER BY l.title_norm
        """,
    )
    fun listingsPaged(storeId: StoreId): PagingSource<Int, ListingRow>

    /** Like [byCategory], paged and with invalidation. See [listingsPaged]. */
    @Query(
        """
        SELECT l.*, a.icon_url AS icon_url FROM store_listings AS l
        LEFT JOIN apps AS a ON a.app_key = l.app_key
        WHERE l.store_id = :storeId AND l.categories LIKE '%"' || :category || '"%'
        ORDER BY l.title_norm
        """,
    )
    fun byCategoryPaged(storeId: StoreId, category: String): PagingSource<Int, ListingRow>

    @Query("SELECT COUNT(*) FROM store_listings WHERE store_id = :storeId")
    suspend fun listingCount(storeId: StoreId): Int

    @Query("SELECT COUNT(*) FROM store_listings WHERE store_id = :storeId")
    fun observeListingCount(storeId: StoreId): Flow<Int>

    @Query("SELECT * FROM app_versions WHERE listing_id = :listingId ORDER BY version_code DESC")
    suspend fun versions(listingId: Long): List<AppVersionEntity>

    @Query("SELECT * FROM app_versions WHERE listing_id = :listingId AND version_ref = :versionRef")
    suspend fun version(listingId: Long, versionRef: String): AppVersionEntity?

    /**
     * A **signal**, not a datum: it re-emits every time the catalogue changes.
     *
     * The number it carries means nothing and must not be read — two different catalogues can
     * perfectly well produce the same count. What matters is that Room re-emits: a `@Query`'s
     * invalidation covers every table the query names, subqueries included, so this re-emits both
     * when a listing changes and when its versions do.
     *
     * It serves whoever computes something in Kotlin that depends on both tables — "is there an
     * update for this app?" — and therefore cannot rely on the invalidation of a query reading a
     * single table.
     */
    @Query("SELECT (SELECT COUNT(*) FROM store_listings) + (SELECT COUNT(*) FROM app_versions)")
    fun observeCatalogRevision(): Flow<Long>
}
